### ISSUE TITLE
Z banding

### ISSUE THREAD

**Issue by avedran** [Roycinger/V0-Umbilical-LGX_Lite#1]
Sorry to drop in this project but just wondering have you resolved that voron z banding issue ?

**Comment by Roycinger** [comment]
Hi,
unfortunately not. 
There's an entire channel in the Voron Discord where this issue is discussed:
https://discordapp.com/channels/460117602945990666/832639170328526899

My personal opinion is that the (original) Afterburner has a huge impact on this. The design is not well thought of, imho. 
I recommend using a proper extruder design like an LGX (Lite) or an Orbiter v2.
Hope that helps!
